version: "3.7"

services:
  # WebApp & DAPR Sidecar
  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PRODUCTS_APP_ID=productsapi
      - CART_STORE=redis_statestore
      - CART_EVENT_BUS=rabbitmqbus/cart_checkout
    ports:
      - "5011:80"

  webapp_dapr:
    image: "daprio/daprd:1.5.0"
    command:
      [
        "./daprd",
        "-app-id", "webapp",
        "-app-port", "80",
        "-config", "/dapr/dapr_config.yaml",
        "-components-path", "/dapr/components",
      ]
    volumes:
      - "./infrastructure/dapr:/dapr"
    depends_on:
      - webapp
    network_mode: "service:webapp"
    env_file:
      - .env


  # ProductApi & DAPR Sidecar
  productsapi:
    build:
      context: ./ProductApi
      dockerfile: Dockerfile
    container_name: productsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5021:80"

  productsapi_dapr:
    image: "daprio/daprd:1.5.0"
    command:
      [
        "./daprd",
        "-app-id", "productsapi",
        "-app-port", "80",
        "-config", "/dapr/dapr_config.yaml",
        "-components-path", "/dapr/components",
      ]
    volumes:
      - "./infrastructure/dapr:/dapr"
    depends_on:
      - productsapi
    network_mode: "service:productsapi"
    env_file:
      - .env


  # OrderService & DAPR Sidecar
  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: orderservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CART_EVENT_BUS=rabbitmqbus/cart_checkout
    ports:
      - "5031:80"

  orderservice_dapr:
    image: "daprio/daprd:1.5.0"
    command:
      [
        "./daprd",
        "-app-id", "orderservice",
        "-app-port", "80",
        "-config", "/dapr/dapr_config.yaml",
        "-components-path", "/dapr/components",
      ]
    volumes:
      - "./infrastructure/dapr:/dapr"
    depends_on:
      - orderservice
    network_mode: "service:orderservice"
    env_file:
      - .env


networks:
  default:
    external:
      name: dapr_network