version: "3.7"

services:
  # MongoDB
  si_mongodb:
    container_name: si_mongodb
    image: "mongo:4.4-bionic"
    env_file:
      - ./infrastructure/.env.mongodb
    volumes:
      - ./infrastructure/si-mongodb-entrypoint/initial_products.json:/data/initial_products.json
      - ./infrastructure/si-mongodb-entrypoint/initial_products_dapr.json:/data/initial_products_dapr.json
      - ./infrastructure/si-mongodb-entrypoint/populate.sh:/docker-entrypoint-initdb.d/populate.sh
      - ./infrastructure/si-mongodb-entrypoint/init.js:/docker-entrypoint-initdb.d/init.js
      - ./si_mongodb/data/db:/data/db
    ports:
      - "27017:27017"
  
      
  # Zipkin
  zipkin:
    container_name: "zipkin_service"
    image: "openzipkin/zipkin:2.23.2"
    ports:
      - 9411:9411


  # Redis
  si_redis:
    container_name: "si_redis"
    image: "redis:6.2-alpine"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./infrastructure/redis.conf:/usr/local/etc/redis/redis.conf


  # RabbitMQ
  si_rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: "si_rabbitmq"
    hostname: "si_rabbitmq"
    env_file:
      - ./infrastructure/.env.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


networks:
  default:
    name: dapr_network
    driver: bridge