#https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongodb_store
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: mongodbHost
      key: mongodbHost
  - name: username
    secretKeyRef:
      name: mongodbUsr
      key: mongodbUsr
  - name: password
    secretKeyRef:
      name: mongodbPwd
      key: mongodbPwd
  - name: databaseName
    value: "app_db"
  - name: collectionName
    value: "products_dapr"
auth:
  secretStore: localsecrets