apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmqbus
  namespace: default
spec:
  type: pubsub.rabbitmq
  metadata:
    - name: host
      secretKeyRef:
        name: rabbitMqConnString
        key: rabbitMqConnString
    - name: consumerID
      value: "order_consumer"
    - name: durable
      value: false
    - name: deletedWhenUnused
      value: false
    - name: autoAck
      value: false
    - name: requeueInFailure
      value: true
    - name: backOffPolicy
      value: "exponential"
    - name: backOffMaxRetries
      value: 5
    - name: backOffInitialInterval
      value: 500
auth:
  secretStore: localsecrets