apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis_statestore
  namespace: default
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: si_redis:6379
    - name: redisPassword
      secretKeyRef:
        name: redisPassword
        key: redisPassword
    - name: ttlInSeconds
      value: 21600 #6 hours
    - name: maxRetries
      value: 3
    - name: redisMinRetryInterval
      value: "8ms"
    - name: actorStateStore
      value: "true"
auth:
  secretStore: localsecrets