apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: si_redis:6379
    - name: redisPassword
      secretKeyRef:
        name: redisPassword
        key: redisPassword
auth:
  secretStore: localsecrets